version: '3'

services:
  web:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
        - WEBHOOK_SECRET=whsec_oNUBClYDh4XalAth8xIZQBpS6ceMMp4i
        - OPENAI_API_KEY=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
        - TEST_STRIPE_KEY=sk_test_51NJcbbD1RPWlDlnhXqjIuP8aAsbR3u08EO83FB2FHpfhG8nCgsUbD0fWolN5ifoptsh3ZZsKwOPHzHf1z4P1spU900V7doveLa
        - SMTP_PASSWORD=fntqybkejdfuwida
    volumes:
        - ./:/app
    networks:
      - redis_network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - redis_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d/django.conf:/etc/nginx/conf.d/django.conf:ro
    networks:
      - redis_network

networks:
  redis_network:
