version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
        - WEBHOOK_SECRET=whsec_oNUBClYDh4XalAth8xIZQBpS6ceMMp4i
        - OPENAI_API_KEY=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
        - TEST_STRIPE_KEY=sk_test_51NJcbbD1RPWlDlnhXqjIuP8aAsbR3u08EO83FB2FHpfhG8nCgsUbD0fWolN5ifoptsh3ZZsKwOPHzHf1z4P1spU900V7doveLa
        - SMTP_PASSWORD=fntqybkejdfuwida
    volumes:
        - ./aurora:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: auroraappdb
      POSTGRES_USER: bsolomon
      POSTGRES_PASSWORD: "@Aurora24"

  redis:
    image: redis:6

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
